version: '3.8'

services:
  python-vote-app:
    build:
      context: ./vote
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      - SOME_ENV_VAR=value
    networks:
      - app-network

  java-worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    environment:
      - SOME_ENV_VAR=value
    networks:
      - app-network

  nodejs-result-app:
    build:
      context: ./result
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - SOME_ENV_VAR=value
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
